spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_control_service_test?user=postgres&password=postgres
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
