name: Test App

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  docker-hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          ignore: ${{ inputs.ignore-rules }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Run Detekt
        run: ./gradlew detekt

  unit-test:
    runs-on: ubuntu-latest
    needs: [docker-hadolint, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Run unit tests
        run: ./gradlew test -i

#  integration-test:
#    services:
#      postgres_db:
#        image: postgres:16.1-alpine
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: financial_control_service_test
#        ports:
#          - 5432:5432
#    runs-on: ubuntu-latest
#    needs: [ docker-hadolint, lint ]
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'corretto'
#          cache: 'gradle'
#      - name: Run integration tests
#        run: ./gradlew integrationTest -i

  mutation-test:
    runs-on: ubuntu-latest
    needs: [docker-hadolint, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Run mutation tests
        run: ./gradlew pitest
